spring.application.name=personalized-data-api

# Active profile
spring.profiles.active=local

# ------------------------------------------------------------------
# Actuator
# ------------------------------------------------------------------
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true

# ------------------------------------------------------------------
# SpringDoc / Swagger
# ------------------------------------------------------------------
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/v3/api-docs

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect