# ------------------------------------------------------------------
# Server
# ------------------------------------------------------------------
server.port=${SERVER_PORT:8080}

# ------------------------------------------------------------------
# MySQL
# ------------------------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=WARN

# ------------------------------------------------------------------
# JWT
# ------------------------------------------------------------------
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:36000}

# ------------------------------------------------------------------
# Application User
# ------------------------------------------------------------------
security.user.name=${SECURITY_USERNAME}
security.user.password=${SECURITY_PASSWORD}